{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "ralph.fullname" . }}-cert
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    {{- if .host }}
    - {{ .host }}
    {{- end }}
    {{- end }}
{{- end }}
