{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "ralph.fullname" . }}-gcpsm
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.gcpProjectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.clusterLocation }}
          clusterName: {{ .Values.externalSecrets.clusterName }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName }}
{{- end }}
