{{- if .Values.externalSecrets.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  labels:
    {{- include "ralph.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: external-secrets-operator@{{ .Values.externalSecrets.gcpProjectID }}.iam.gserviceaccount.com
{{- end }}
